services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PwdSql123"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "PwdSeq123"
    volumes:
      - seq_data:/data
    ports:
      - "5341:5341"
      - "8081:80"

  caseitau-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caseitau-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CaseItau;User Id=sa;Password=PwdSql123;TrustServerCertificate=True"
      OpenTelemetry__OtlpEndpoint: "http://seq:5341/ingest/otlp/v1/traces"
      Serilog__WriteTo__1__Args__serverUrl: "http://seq:5341"
    depends_on:
      - sqlserver
      - seq

volumes:
  sqlserver_data:
  seq_data:
