// <auto-generated />
using CaseItau.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseItau.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307010000_SeedTipoFundo")]
    partial class SeedTipoFundo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseItau.Domain.Entities.Fundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODIGO");

                    b.Property<int>("CodigoTipo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_TIPO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("Patrimonio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PATRIMONIO");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoTipo");

                    b.ToTable("FUNDO");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TipoFundo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NOME");

                    b.HasKey("Codigo");

                    b.ToTable("TIPO_FUNDO");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Nome = "RENDA FIXA"
                        },
                        new
                        {
                            Codigo = 2,
                            Nome = "ACOES"
                        },
                        new
                        {
                            Codigo = 3,
                            Nome = "MULTI MERCADO"
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.Fundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.TipoFundo", "TipoFundo")
                        .WithMany("Fundos")
                        .HasForeignKey("CodigoTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFundo");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TipoFundo", b =>
                {
                    b.Navigation("Fundos");
                });
#pragma warning restore 612, 618
        }
    }
}
